// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           27
// Async Callback:                       1
// Total number of exported functions:  29

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    savings_account
    (
        init => init
        lend => lend
        borrow => borrow
        repay => repay
        withdraw => withdraw
        lenderClaimRewards => lender_claim_rewards
        getPenaltyAmount => get_penalty_amount_view
        getLenderClaimableRewards => get_lender_claimable_rewards_view
        getLoadToValuePercentage => loan_to_value_percentage
        setPriceAggregatorAddress => set_price_aggregator_address
        getAggregatorAddress => price_aggregator_address
        claimStakingRewards => claim_staking_rewards
        convertStakingTokenToStablecoin => convert_staking_token_to_stablecoin
        getDelegationScAddress => delegation_sc_address
        getDexSwapScAddress => dex_swap_sc_address
        getLastStakingRewardsClaimEpoch => last_staking_rewards_claim_epoch
        getLastStakingTokenConvertEpoch => last_staking_token_convert_epoch
        getLenderRewardsPercentagePerEpoch => lender_rewards_percentage_per_epoch
        issueLendToken => issue_lend_token
        issueBorrowToken => issue_borrow_token
        getStablecoinTokenId => stablecoin_token_id
        getLiquidStakingTokenId => liquid_staking_token_id
        getStakedTokenId => staked_token_id
        getLendTokenId => lend_token
        getBorrowTokenId => borrow_token
        getStablecoinReserves => stablecoin_reserves
        getLentAmount => lent_amount
        getBorowedAmount => borrowed_amount
    )
}

multiversx_sc_wasm_adapter::async_callback! { savings_account }
