[package]
name = "dex-mock"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@elrond.com>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.45.2"

[dependencies.multiversx-sc-modules]
version = "0.45.2"